export const ADD_CURRENCY = 'ADD_CURRENCY';
export const REMOVE_CURRENCY = 'REMOVE_CURRENCY';
export const GET_RATES_SUCCESS = 'GET_RATES_SUCCESS';
export const GET_RATES_REQUEST = 'GET_RATES_REQUEST';
